name: Release

on:
  workflow_dispatch:

jobs:
  broadcast_release:
    runs-on: macos-latest

    steps:
      - name: Homebrew Cask Bumper
        run: |
          LATEST_VERSION=$(gh release view -R iamzjt-front-end/fund-pulse --json tagName -q '.tagName' | sed 's/^v//')
          brew update
          brew bump-cask-pr --version "$LATEST_VERSION" fund-pulse
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_GH_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GH_TOKEN }}
